name: CI

####################
# Start the job on #
####################
on:
  push:
  pull_request:
    branches: [main]

###################
# Set Global Envs #
###################
env:
  NODE_VERSION: '12'

############
# Set Jobs #
############
jobs:
  ##############
  # Define Job #
  ##############
  CI:
    name: CI
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:
      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      #################
      # Setup Node JS #
      #################
      - name: Setup Node JS
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: '@qbcart'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.QBC_GITHUB_PACKAGES }}

      ################
      # Install Deps #
      ################
      - name: Install Deps
        shell: bash
        run: npm install

      #################
      # Build Project #
      #################
      - name: Build Project
        shell: bash
        run: npm run build

      #############
      # Lint Code #
      #############
      - name: Lint Code
        shell: bash
        run: npm run lint

      #############
      # Run Tests #
      #############
      - name: Run Tests
        shell: bash
        run: npm run test:ci
