name: CI

##############################################################
# Triggers when push changes occur in specified branch paths #
##############################################################
on:
  push:
    branches-ignore:
      - main
      - '!v[0-9]+.[0-9]+.[0-9]+*'
    paths:
      - 'src/**'
      - 'snowpack.config.js'

############
# Set Jobs #
############
jobs:
  ##############
  # Define Job #
  ##############
  continuos-integration:
    name: Continuos Integration
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:
      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      #################
      # Setup Node JS #
      #################
      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ fromJSON(secrets.DEV_ESM).node }}

      ################
      # Install Deps #
      ################
      - name: Install Deps
        working-directory: .
        shell: bash
        run: npm install

      #############
      # Lint Code #
      #############
      - name: Lint Code
        working-directory: .
        shell: bash
        run: npm run lint

      ################
      # Check Format #
      ################
      - name: Check Format
        working-directory: .
        shell: bash
        run: npm run format:check

      #############
      # Build ESM #
      #############
      - name: Build ESM
        working-directory: .
        shell: bash
        run: npm run build
        env:
          SNOWPACK_PUBLIC_STREAMING_URL: ${{ fromJSON(secrets.DEV_ESM).storageUrl }}

      #############
      # Run Tests #
      #############
      - name: Run Tests
        working-directory: .
        shell: bash
        run: npm run test:ci

      ###############
      # Azure Login #
      ###############
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      ######################
      # Publish To Dev ESM #
      ######################
      - name: Publish To Dev ESM
        working-directory: .
        shell: bash
        run: |
          az account set --subscription ${{ fromJSON(secrets.DEV_ESM).subscriptionId }}
          az storage blob delete-batch --account-name ${{ fromJSON(secrets.DEV_ESM).storageName }} --source '$web' --pattern 'utils/*'
          az storage blob upload-batch --account-name ${{ fromJSON(secrets.DEV_ESM).storageName }} --source 'publish_esm' --destination '$web/utils' --auth-mode key --content-cache 'no-store, max-age=0'
