name: Demo

######################################
# Triggers when changes occur in src #
######################################
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

###################
# Set Global Envs #
###################
env:
  NODE_VERSION: '14'
  DEMO_STORAGE_NAME: qbcdemo
  SUBSCRIPTION_ID: ${{ secrets.DEMO_SUBSCRIPTION_ID }}

############
# Set Jobs #
############
jobs:
  ##############
  # Define Job #
  ##############
  publish-demo:
    name: Publish Demo
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:
      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      #################
      # Setup Node JS #
      #################
      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      ################
      # Install Deps #
      ################
      - name: Install Deps
        working-directory: .
        shell: bash
        run: npm install

      #############
      # Build ESM #
      #############
      - name: Build ESM
        working-directory: .
        shell: bash
        run: npm run build

      ###############
      # Azure Login #
      ###############
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      ###############################
      # Publish ESM To Demo Storage #
      ###############################
      - name: Publish ESM To Demo Storage
        working-directory: .
        shell: bash
        run: |
          az account set --subscription ${{ env.SUBSCRIPTION_ID }}
          az storage blob delete-batch --account-name ${{ env.DEMO_STORAGE_NAME }} --source '$web' --pattern 'utils/*'
          az storage blob upload-batch --account-name ${{ env.DEMO_STORAGE_NAME }} --source 'dist/esm' --destination '$web/utils' --auth-mode key --content-cache 'no-store, max-age=0'
