name: Release

###################################################
# Start the job on semantic versioned branch push #
###################################################
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

###################
# Set Global Envs #
###################
env:
  node_version: '14'
  STORAGE_NAME: ${{ secrets.ESM_STORAGE_NAME }}
  SUBSCRIPTION_ID: ${{ secrets.QBC_SUBSCRIPTION_ID }}

############
# Set Jobs #
############
jobs:
  ##############
  # Define Job #
  ##############
  release:
    name: Release
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:
      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      ###############
      # Get Version #
      ###############
      - name: Get Version
        shell: bash
        run: |
          pattern="refs/heads/"
          ver="${github_ref/$pattern/}"
          echo $ver
          echo "new_version=$ver" >> $GITHUB_ENV
        env:
          github_ref: ${{ github.ref }}

      #################
      # Setup Node JS #
      #################
      - name: Setup Node JS
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org
          scope: '@qbcart'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      ################
      # Install Deps #
      ################
      - name: Install Deps
        working-directory: .
        shell: bash
        run: npm install

      #################
      # Build Package #
      #################
      - name: Build Package
        working-directory: .
        shell: bash
        run: npm run build

      ######################
      # Copy Package Files #
      ######################
      - name: Copy Package Files
        working-directory: .
        shell: bash
        run: |
          cp package.json dist
          cp README.md dist

      ##################
      # Publish To NPM #
      ##################
      - name: Publish To NPM
        working-directory: dist
        shell: bash
        run: |
          npm version $ver --allow-same-version
          echo 'VER:' $ver
          npm publish --access public
        env:
          ver: ${{ env.new_version }}

      #########################
      # Create GitHub Release #
      #########################
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.new_version }}
          release_name: ${{ env.new_version }}
          body_path: RELEASE.md
          draft: false
          prerelease: ${{ contains(env.new_version, 'alpha') || contains(env.new_version, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ###############
      # Azure Login #
      ###############
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      ##########################
      # Publish ESM To Storage #
      ##########################
      - name: Publish ESM To Storage
        working-directory: .
        shell: bash
        run: |
          az account set --subscription ${{ env.SUBSCRIPTION_ID }}
          az storage blob delete-batch --account-name ${{ env.STORAGE_NAME }} --source '$web' --pattern 'utils/*'
          az storage blob upload-batch --account-name ${{ env.STORAGE_NAME }} --source 'dist/esm' --destination '$web/utils' --auth-mode key --content-cache 'max-age=3600, must-revalidate'
